### ISSUE TITLE
cannot support MonoAndroid Version v8.0

### ISSUE THREAD

**Issue by zmklark** [mathieumack/MvvX.Plugins.HockeyApp#9]
Unable to install the package "hockeysd.core 4.1.5". You are trying to install this package into a project targeted for "MonoAndroid,Version=v8.0", but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by mathieumack** [comment]
Hi, a new package version is currently in build.
Could you check that the new package configuration is ok for Android ?
New version published : 2018.10307.11231.59

**Comment by mathieumack** [comment]
Hi, Can I close the issue ?
